### ISSUE TITLE
KITTI dataset config.py file IndentationError

### ISSUE THREAD

**Issue by santipuch590** [dvazquezcvc/mcv-m5#10]
On the KITTI dataset's configuration file (`config.py`) there is a `IndentationError` that prevents us from training any network using this dataset.

The error is caused by a unnecessary indent just before the **categories** are defined.

```
(...)
rgb_rescale     = 1/255.           # Scalar to divide and set range 0-1

    categories = {
        0: 'background',
        1: 'Car',
        2: 'Van',
        3: 'Truck',
        4: 'Pedestrian',
        5: 'Person_sitting',
        6: 'Cyclist',
        7: 'Tram'
        }

(...)
```

**Comment by xianlopez** [comment]
I put it to work changing that by:

(...)
rgb_rescale     = 1/255.           # Scalar to divide and set range 0-1

# Classes
classes = {
	0: 'background',
	1: 'Car',
	2: 'Van',
	3: 'Truck',
	4: 'Pedestrian',
	5: 'Person_sitting',
	6: 'Cyclist',
	7: 'Tram'
	}
(...)

**Comment by dvazquezcvc** [comment]
Changed in the served. Thanks :)
