### ISSUE TITLE
Error training with KITTI

### ISSUE THREAD

**Issue by xianlopez** [dvazquezcvc/mcv-m5#11]
We got the following error when trying to train a network in KITTI dataset:
```
OSError: [Errno 2] No such file or directory: '/home/master/m5_project/data/Datasets/classification/KITTI/test/background'
```

We solved it by manually creating a folder called test, with an empty folder inside for each class.

**Comment by dvazquezcvc** [comment]
I have created the test folder in the shared folder. Thanks
