### ISSUE TITLE
Simple ITK missing

### ISSUE THREAD

**Issue by GonzaBCCC** [dvazquezcvc/mcv-m5#3]
Hello, i have found the following error regarding Simple ITK when launching train.py:

Traceback (most recent call last):
  File "train.py", line 12, in <module>
    from tools.dataset_generators import Dataset_Generators
  File "/home/master/workspace/code/tools/dataset_generators.py", line 1, in <module>
    from tools.data_loader import ImageDataGenerator
  File "/home/master/workspace/code/tools/data_loader.py", line 13, in <module>
    import SimpleITK as sitk
ImportError: No module named SimpleITK

I proceeded to search Simple ITK on my own, but just wanted to issue the situation.

Regards

**Comment by dvazquezcvc** [comment]
Hi,

simpleITK is the ITK library. ITK is an image processing library (Similar to opencv). We use SimpleITK for the image warping of the data augmentation (Something we added to the standard data augmentation of Keras).

To enable simpleITK you need to install it:
pip install SimpleITK --user

I have added it to the installation document
